@baseUrl = http://localhost:3000
@accessToken = {{authenticate.response.body.data.token}}

# @name create_account
POST {{baseUrl}}/register
Content-Type: application/json

{
	"name": "du,,y doe",
	"email": "du,,ydoe@example.com",
	"password": "password123"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
	"email": "johndoe@example.com",
	"password": "password123"
}

###

# @name fetch_accounts
GET {{baseUrl}}/accounts?page=1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

# @name profile
GET {{baseUrl}}/me
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

# @name delete_account
DELETE {{baseUrl}}/accounts/254ec062-e911-4c31-80a2-83d845f9ead9
Content-Type: application/json
Authorization: Bearer {{accessToken}}
